
<!-- content -->
<table BORDER=0 CELLSPACING=10 CELLPADDING=0 WIDTH="100%" >
<tr width=80% valign=top><td>

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="center">
<font color="#000000"><b>sorted by: <a href="index.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-21&days=1&by=Date">Date</a> | <a href="index.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-21&days=1&by=Importance">Importance</a> | <a href="index.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-21&days=1&by=Urgency">Urgency</a> | <a href="index.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-21&days=1&by=Name">Name</a>
</b></font>
</td></tr>
<!-- box title end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="center">
<font color="#000000"><b><a href="index.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-14&days=1&by=Date">&lt;&nbsp;Week</a> | <a href="index.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-20&days=1&by=Date">&lt;&nbsp;Day</a> | <a href="index.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-21&days=1&cnt=15&by=Date">&lt;&nbsp;15 Apps</a> | <a href="index.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&by=Date">Today</a> | 15&nbsp;Apps&nbsp;&gt; | Day&nbsp;&gt; | Week&nbsp;&gt;</b></font>
</td></tr>
<!-- box title end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr valign=bottom><td width=30%><b><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=508">SourceWell 1.0.12</a> (Development)</b></td>
<td width=70% align=right>
<img src="images/importance.png" alt="Importance"><b>(239)</b>
&nbsp;<img src="images/bell.png" alt="Urgency:high"><img src="images/bell.png" alt="Urgency:high">&nbsp;&nbsp;<a href="redirect.php3?id=508&type=homepage_cnt&url=http://sourcewell.berlios.de/html/" target=_blank><img src="images/html.png" border=0 alt="Homepage"></a>
&nbsp;&nbsp;<a href="redirect.php3?id=508&type=download_cnt&url=http://developer.berlios.de/project/filelist.php?group_id=23" target=_blank><img src="images/binary2.png" border=0 alt="Download"></a>
&nbsp;&nbsp;<a href="redirect.php3?id=508&type=changelog_cnt&url=http://sourcewell.berlios.de/doc/CHANGELOG" target=_blank><img src="images/info.png" border=0 alt="Changelog"></a>
&nbsp;&nbsp;<a href="cmtapp.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&id=508"><img src="images/txt.png" border=0 alt="Comments"></a> </a>
&nbsp;&nbsp;<a href="appbycat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&section=Networking&category=PHP"><b>Networking/PHP</b></a>
</td></tr>
</table>
</td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<b>by <a href="mailto:nobody@noplace.not">anonymous</a> - Friday, 21. December 2001, 17:10:58 CET</b>
<p>SourceWell is a highly configurable, well documented software announcement and retrieval system entirely writen in PHP3 and database independent. It includes user authentication and autherization system (anonymous/user/editor/admin), sessions with and without cookies, high configurability, multilangual support, ease of administration, RDF-type document backend, advanced statistics, announcing mailing lists, application indexing by sections and many other useful features.
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr valign=bottom><td width=30%><b><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1747">mas calentito me pongo acelero3</a> (Stable)</b></td>
<td width=70% align=right>
<img src="images/importance.png" alt="Importance"><b>(2)</b>
&nbsp;<img src="images/bell.png" alt="Urgency:medium">&nbsp;&nbsp;<a href="cmtapp.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&id=1747"><img src="images/txt.png" border=0 alt="Comments"></a> </a>
&nbsp;&nbsp;<a href="appbycat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&section=Console&category=Backup"><b>Console/Backup</b></a>
</td></tr>
</table>
</td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<b>by <a href="mailto:nobody@noplace.not">anonymous</a> - Thursday, 20. December 2001, 16:06:15 CET</b>
<p>
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr valign=bottom><td width=30%><b><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1736">123456 w3e</a> (Stable)</b></td>
<td width=70% align=right>
<img src="images/importance.png" alt="Importance"><b>(1)</b>
&nbsp;<img src="images/bell.png" alt="Urgency:medium">&nbsp;&nbsp;<a href="cmtapp.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&id=1736"><img src="images/txt.png" border=0 alt="Comments"></a> </a>
&nbsp;&nbsp;<a href="appbycat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&section=Console&category=Backup"><b>Console/Backup</b></a>
</td></tr>
</table>
</td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<b>by <a href="mailto:nobody@noplace.not">anonymous</a> - Thursday, 20. December 2001, 14:26:01 CET</b>
<p>
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr valign=bottom><td width=30%><b><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1745">bveeeeeeeeeeenga 123</a> (Stable)</b></td>
<td width=70% align=right>
<img src="images/importance.png" alt="Importance"><b>(1)</b>
&nbsp;<img src="images/bell.png" alt="Urgency:medium">&nbsp;&nbsp;<a href="cmtapp.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&id=1745"><img src="images/txt.png" border=0 alt="Comments"></a> </a>
&nbsp;&nbsp;<a href="appbycat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&section=Console&category=Backup"><b>Console/Backup</b></a>
</td></tr>
</table>
</td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<b>by <a href="mailto:grex@scouts-es.org">grex</a> - Thursday, 20. December 2001, 14:24:32 CET</b>
<p>
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr valign=bottom><td width=30%><b><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1744">yaf 123456</a> (Stable)</b></td>
<td width=70% align=right>
<img src="images/importance.png" alt="Importance"><b>(0)</b>
&nbsp;<img src="images/bell.png" alt="Urgency:medium">&nbsp;&nbsp;<a href="cmtapp.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&id=1744"><img src="images/txt.png" border=0 alt="Comments"></a> </a>
&nbsp;&nbsp;<a href="appbycat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&section=Console&category=Backup"><b>Console/Backup</b></a>
</td></tr>
</table>
</td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<b>by <a href="mailto:grex@scouts-es.org">grex</a> - Thursday, 20. December 2001, 14:19:05 CET</b>
<p>
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr valign=bottom><td width=30%><b><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1743">lalal q2e</a> (Stable)</b></td>
<td width=70% align=right>
<img src="images/importance.png" alt="Importance"><b>(1)</b>
&nbsp;<img src="images/bell.png" alt="Urgency:medium">&nbsp;&nbsp;<a href="cmtapp.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&id=1743"><img src="images/txt.png" border=0 alt="Comments"></a> </a>
&nbsp;&nbsp;<a href="appbycat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&section=Console&category=Backup"><b>Console/Backup</b></a>
</td></tr>
</table>
</td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<b>by <a href="mailto:grex@scouts-es.org">grex</a> - Thursday, 20. December 2001, 14:17:16 CET</b>
<p>
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr valign=bottom><td width=30%><b><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1742">bala oveja</a> (Stable)</b></td>
<td width=70% align=right>
<img src="images/importance.png" alt="Importance"><b>(1)</b>
&nbsp;<img src="images/bell.png" alt="Urgency:medium">&nbsp;&nbsp;<a href="cmtapp.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&id=1742"><img src="images/txt.png" border=0 alt="Comments"></a> </a>
&nbsp;&nbsp;<a href="appbycat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&section=Console&category=Backup"><b>Console/Backup</b></a>
</td></tr>
</table>
</td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<b>by <a href="mailto:grex@scouts-es.org">grex</a> - Thursday, 20. December 2001, 14:04:58 CET</b>
<p>
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr valign=bottom><td width=30%><b><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1741">bras 1.23</a> (Stable)</b></td>
<td width=70% align=right>
<img src="images/importance.png" alt="Importance"><b>(1)</b>
&nbsp;<img src="images/bell.png" alt="Urgency:medium">&nbsp;&nbsp;<a href="cmtapp.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&id=1741"><img src="images/txt.png" border=0 alt="Comments"></a> </a>
&nbsp;&nbsp;<a href="appbycat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&section=Console&category=Backup"><b>Console/Backup</b></a>
</td></tr>
</table>
</td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<b>by <a href="mailto:grex@scouts-es.org">grex</a> - Thursday, 20. December 2001, 14:01:51 CET</b>
<p>
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr valign=bottom><td width=30%><b><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1740">grex we3</a> (Stable)</b></td>
<td width=70% align=right>
<img src="images/importance.png" alt="Importance"><b>(1)</b>
&nbsp;<img src="images/bell.png" alt="Urgency:medium">&nbsp;&nbsp;<a href="cmtapp.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&id=1740"><img src="images/txt.png" border=0 alt="Comments"></a> </a>
&nbsp;&nbsp;<a href="appbycat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&section=Console&category=Backup"><b>Console/Backup</b></a>
</td></tr>
</table>
</td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<b>by <a href="mailto:grex@scouts-es.org">grex</a> - Thursday, 20. December 2001, 14:00:15 CET</b>
<p>asdfasdf
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr valign=bottom><td width=30%><b><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1739">boing bafa</a> (Stable)</b></td>
<td width=70% align=right>
<img src="images/importance.png" alt="Importance"><b>(1)</b>
&nbsp;<img src="images/bell.png" alt="Urgency:medium">&nbsp;&nbsp;<a href="cmtapp.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&id=1739"><img src="images/txt.png" border=0 alt="Comments"></a> </a>
&nbsp;&nbsp;<a href="appbycat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&section=Console&category=Backup"><b>Console/Backup</b></a>
</td></tr>
</table>
</td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<b>by <a href="mailto:nobody@noplace.not">anonymous</a> - Thursday, 20. December 2001, 13:46:57 CET</b>
<p>
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr valign=bottom><td width=30%><b><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1738">Con Trim 123.23</a> (Stable)</b></td>
<td width=70% align=right>
<img src="images/importance.png" alt="Importance"><b>(1)</b>
&nbsp;<img src="images/bell.png" alt="Urgency:medium">&nbsp;&nbsp;<a href="redirect.php3?id=1738&type=homepage_cnt&url=con trim" target=_blank><img src="images/html.png" border=0 alt="Homepage"></a>
&nbsp;&nbsp;<a href="redirect.php3?id=1738&type=download_cnt&url=con trim" target=_blank><img src="images/binary2.png" border=0 alt="Download"></a>
&nbsp;&nbsp;<a href="redirect.php3?id=1738&type=changelog_cnt&url=con trim" target=_blank><img src="images/info.png" border=0 alt="Changelog"></a>
&nbsp;&nbsp;<a href="cmtapp.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&id=1738"><img src="images/txt.png" border=0 alt="Comments"></a> <b>[1]</b></a>
&nbsp;&nbsp;<a href="appbycat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&section=Console&category=Backup"><b>Console/Backup</b></a>
</td></tr>
</table>
</td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<b>by <a href="mailto:nobody@noplace.not">anonymous</a> - Thursday, 20. December 2001, 13:06:33 CET</b>
<p>con trim  

        con trim                                                        con trim
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr valign=bottom><td width=30%><b><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=692">GtkExtra-- 0.9.2</a> (Stable)</b></td>
<td width=70% align=right>
<img src="images/importance.png" alt="Importance"><b>(17)</b>
&nbsp;<img src="images/bell.png" alt="Urgency:medium">&nbsp;&nbsp;<a href="redirect.php3?id=692&type=homepage_cnt&url=http://gtkextramm.sourceforge.net" target=_blank><img src="images/html.png" border=0 alt="Homepage"></a>
&nbsp;&nbsp;<a href="redirect.php3?id=692&type=download_cnt&url=http://ftp1.sourceforge.net/gtkextramm/gtkextramm-0.9.2.tar.gz" target=_blank><img src="images/binary2.png" border=0 alt="Download"></a>
&nbsp;&nbsp;<a href="redirect.php3?id=692&type=changelog_cnt&url=http://sourceforge.net/news/?group_id=1737" target=_blank><img src="images/info.png" border=0 alt="Changelog"></a>
&nbsp;&nbsp;<a href="cmtapp.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&id=692"><img src="images/txt.png" border=0 alt="Comments"></a> </a>
&nbsp;&nbsp;<a href="appbycat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&section=GNOME&category=Development"><b>GNOME/Development</b></a>
</td></tr>
</table>
</td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<b>by <a href="mailto:grex@scouts-es.org">grex</a> - Tuesday, 18. December 2001, 15:26:41 CET</b>
<p>GtkExtra-- provides C++ wrappers for GtkExtra, for use with Gtk--. This includes the GtkPlot and GtkSheet widgets, among others.
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr valign=bottom><td width=30%><b><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=708">Bastille Linux 1.3.0.pre5</a> (Development)</b></td>
<td width=70% align=right>
<img src="images/importance.png" alt="Importance"><b>(67)</b>
&nbsp;<img src="images/bell.png" alt="Urgency:medium">&nbsp;&nbsp;<a href="redirect.php3?id=708&type=homepage_cnt&url=http://www.bastille-linux.org" target=_blank><img src="images/html.png" border=0 alt="Homepage"></a>
&nbsp;&nbsp;<a href="redirect.php3?id=708&type=download_cnt&url=http://ftp1.sourceforge.net/bastille-linux/Bastille-1.2.0.pre5.tar.bz2" target=_blank><img src="images/binary2.png" border=0 alt="Download"></a>
&nbsp;&nbsp;<a href="redirect.php3?id=708&type=changelog_cnt&url=http://bastille-linux.sourceforge.net/#updates" target=_blank><img src="images/info.png" border=0 alt="Changelog"></a>
&nbsp;&nbsp;<a href="cmtapp.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&id=708"><img src="images/txt.png" border=0 alt="Comments"></a> </a>
&nbsp;&nbsp;<a href="appbycat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&section=Networking&category=Administration"><b>Networking/Administration</b></a>
</td></tr>
</table>
</td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<b>by <a href="mailto:grex@scouts-es.org">grex</a> - Tuesday, 18. December 2001, 15:25:42 CET</b>
<p>Bastille Linux aims to be the most comprehensive, flexible, and educational Security Hardening Program for Red Hat Linux 6.0-6.2 and Mandrake Linux 6.0, 6.1. Virtually every task it performs is optional, providing immense flexibility. It educates the installing admin regarding the topic at hand before asking any question. The interactive nature allows the program to be more thorough when securing, while the educational component produces an admin who is less likely to compromise the increased security
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr valign=bottom><td width=30%><b><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1655">Knights 0.5</a> (Stable)</b></td>
<td width=70% align=right>
<img src="images/importance.png" alt="Importance"><b>(10)</b>
&nbsp;<img src="images/bell.png" alt="Urgency:medium">&nbsp;&nbsp;<a href="redirect.php3?id=1655&type=homepage_cnt&url=http://knights.sourceforge.net/" target=_blank><img src="images/html.png" border=0 alt="Homepage"></a>
&nbsp;&nbsp;<a href="redirect.php3?id=1655&type=download_cnt&url=http://prdownloads.sourceforge.net/knights/knights-0.5.tar.gz" target=_blank><img src="images/binary2.png" border=0 alt="Download"></a>
&nbsp;&nbsp;<a href="redirect.php3?id=1655&type=changelog_cnt&url=http://sourceforge.net/project/shownotes.php?release_id=64232" target=_blank><img src="images/info.png" border=0 alt="Changelog"></a>
&nbsp;&nbsp;<a href="cmtapp.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&id=1655"><img src="images/txt.png" border=0 alt="Comments"></a> </a>
&nbsp;&nbsp;<a href="appbycat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&section=KDE&category=Games"><b>KDE/Games</b></a>
</td></tr>
</table>
</td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<b>by <a href="mailto:grex@scouts-es.org">grex</a> - Tuesday, 18. December 2001, 15:25:06 CET</b>
<p>Knights is a graphical chess interface for KDE2. It supports solitaire chess, play against a chess engine, watching two engines play
  against each other, playing on a chess server, and reviewing of PGN games.
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr valign=bottom><td width=30%><b><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1666">GNU Solfege 1.3.4</a> (Development)</b></td>
<td width=70% align=right>
<img src="images/importance.png" alt="Importance"><b>(3)</b>
&nbsp;<img src="images/bell.png" alt="Urgency:medium">&nbsp;&nbsp;<a href="redirect.php3?id=1666&type=homepage_cnt&url=http://www.solfege.org" target=_blank><img src="images/html.png" border=0 alt="Homepage"></a>
&nbsp;&nbsp;<a href="redirect.php3?id=1666&type=download_cnt&url=ftp://alpha.gnu.org/gnu/solfege/solfege-1.3.4.tar.gz" target=_blank><img src="images/binary2.png" border=0 alt="Download"></a>
&nbsp;&nbsp;<a href="redirect.php3?id=1666&type=changelog_cnt&url=http://www.solfege.org/index.php3?article=changelog" target=_blank><img src="images/info.png" border=0 alt="Changelog"></a>
&nbsp;&nbsp;<a href="cmtapp.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&id=1666"><img src="images/txt.png" border=0 alt="Comments"></a> </a>
&nbsp;&nbsp;<a href="appbycat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&section=X11&category=Sound"><b>X11/Sound</b></a>
</td></tr>
</table>
</td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<b>by <a href="mailto:grex@scouts-es.org">grex</a> - Tuesday, 18. December 2001, 15:23:34 CET</b>
<p>GNU Solfege is *free* eartraining software written in python. The program is designed to be easily extended with lessonfiles (data files), so the user can create new exercises. You can build it as a GNOME App, or just use the gtk+ libraries.
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="center">
<font color="#000000"><b><a href="index.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-14&days=1&by=Date">&lt;&nbsp;Week</a> | <a href="index.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-20&days=1&by=Date">&lt;&nbsp;Day</a> | <a href="index.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-21&days=1&cnt=15&by=Date">&lt;&nbsp;15 Apps</a> | <a href="index.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&by=Date">Today</a> | 15&nbsp;Apps&nbsp;&gt; | Day&nbsp;&gt; | Week&nbsp;&gt;</b></font>
</td></tr>
<!-- box title end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="center">
<font color="#000000"><b>sorted by: <a href="index.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-21&days=1&by=Date">Date</a> | <a href="index.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-21&days=1&by=Importance">Importance</a> | <a href="index.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-21&days=1&by=Urgency">Urgency</a> | <a href="index.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-21&days=1&by=Name">Name</a>
</b></font>
</td></tr>
<!-- box title end -->
</table>
</td></tr></table><br>
<!-- box end -->
</td><td width=20%>

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<center><b><a href="/grex/doc/sourcewell/index_stat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-21&days=1">Friday, 21. Dec</b></center></a></td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=508">SourceWell 1.0.12</a></li>
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<center><b><a href="/grex/doc/sourcewell/index_stat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-20&days=1">Thursday, 20. Dec</b></center></a></td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1747">mas calentito me pongo acelero3</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1736">123456 w3e</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1745">bveeeeeeeeeeenga 123</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1744">yaf 123456</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1743">lalal q2e</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1742">bala oveja</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1741">bras 1.23</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1740">grex we3</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1739">boing bafa</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1738">Con Trim 123.23</a></li>
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<center><b><a href="/grex/doc/sourcewell/index_stat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-18&days=1">Tuesday, 18. Dec</b></center></a></td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=692">GtkExtra-- 0.9.2</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=708">Bastille Linux 1.3.0.pre5</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1655">Knights 0.5</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1666">GNU Solfege 1.3.4</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=618">Getleft 1.0beta1</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=847">vile 9.2r</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1733">GNU nano 1.0.7</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1732">KPercentage 0.1</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=698">GNU TeXmacs 0.3.5.11</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1690">bash programmable completion 20011217</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1731">KLearnSpelling 0.1</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1730">SILC (Server) 0.7.2</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=907">W3Perl 2.86</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=882">MrProject 0.5.0</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=741">Samba 3.0-alpha9</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1729">KMessedWords 1.0.0</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=287">GnuCash 1.6.5</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=753">KOffice 1.1.1</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=897">LinPhone 0.6.0</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=55">XEmacs 21.4.6</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=424">XDrawChem 0.99.7</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1507">gnomeradio 0.99.1</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1709">KOggTag 0.2</a></li>
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->

<!-- box begin -->
<table border=0 cellspacing=0 cellpadding=0 bgcolor="#000000" width="100%" align=center>
<tr><td>
<table border=0 cellspacing="1" cellpadding=3 align="center" width="100%">
<!-- box title begin -->
<tr bgcolor="#CCCCCC"><td align="left">
<center><b><a href="/grex/doc/sourcewell/index_stat.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&start=2001-12-17&days=1">Monday, 17. Dec</b></center></a></td></tr>
<!-- box title end -->
<!-- box body begin -->
<tr bgcolor="#FFFFFF"><td align="left"><font color="#333333">
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1234">gLabels 0.3.4</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=551">Firestarter 0.8.0</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1703">KEuroCalc 0.5.1</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=248">knetfilter 2.2.3</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1371">WebGUI 2.6.0</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=130">PgMarket 2.0.2</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1580">syslinux 1.66pre1</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1728">Kalamaris 0.7.0</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1270">libglade 1.99.5</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=609">AbiWord 0.9.6</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1727">Digital Video Recorder 2.4.9</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=622">Ximian Setup Tools 0.11.0</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1584">Development Linux 2.5 Kernel 2.5.1</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1204">Global File System (GFS) 5.0</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1726">Hewlett-Packard Linux Inkjet Driver 1.0</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1725">GQview image viewer 1.0</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1724">PSGML 1.2.4</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1038">gcompris 0.9.6</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1723">phpESP - Easy Survey Package 1.3 RC2</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=948">Qtella 0.3.3</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1278">Scribus 0.5</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=509">Tora 1.3.0</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=552">Gnumeric 0.99</a></li>
<li><a href="app.php3?SourceWell_Session=98fb69c72a56985f84eec79bd8e49199&appid=1565">Gtktimi 1.5</a></li>
</font></td></tr>
<!-- box body end -->
</table>
</td></tr></table><br>
<!-- box end -->
</td></tr>
</table>
<!-- end content -->
