</td>
</tr>
</table>

<!-- footer -->
<table BORDER=0 CELLSPACING=0 CELLPADDING=2 WIDTH="100%" BGCOLOR="<?php echo $th_navstrip_bgcolor;?>">
<tr>
<td width=23%>&nbsp;</td>
<td ALIGN=CENTER width=54%><span class="titlebar"><font color="<?php echo $th_navstrip_font_color;?>">Copyright
&copy;2001 <a href="<?php echo $org_url;?>" class="maintitlebar" TARGET="_blank"><?php echo $org_name;?></a>.</font></span></td>
<td width=23% align=right><span class="titlebar"><A HREF="html" target="_blank"><FONT COLOR="<?php echo $th_nav_bgcolor;?>"><?php echo $t->translate("System Credits");?></font></<a>&nbsp;</span></td>
</tr>
</table>
<!-- end footer -->

</body>
</html>

<?php
page_close();
?>