</td>
</tr>
</table>

<!-- footer -->
<table border=0 cellspacing=0 cellpadding=2 width="100%" bgcolor="<?php echo $th_navstrip_bgcolor;?>">
<tr>
<td width="15%">&nbsp;</td>
<td align="center" width="70%"><span class="titlebar"><font color="<?php echo $th_navstrip_font_color;?>">Copyright
&copy; 2001-<?php echo date("Y"); ?> <a href="<?php echo $org_url;?>" class="maintitlebar" target="_blank"><?php echo $org_name;?></a></font></span></td>
<td width="15%" align=right><span class="titlebar"><a href="html/" class="maintitlebar" target="_blank"><?php echo $t->translate("System Credits");?></a>&nbsp;</span></td>
</tr>
</table>
<!-- end footer -->

</body>
</html>
