<?php

######################################################################
# SourceWell: Software Announcement & Retrieval System
# ================================================
#
# Copyright (c) 2001-2004 by
#                Lutz Henckel (lutz.henckel@fokus.fraunhofer.de) and
#                Gregorio Robles (grex@scouts-es.org)
#
# BerliOS SourceWell: http://sourcewell.berlios.de
# BerliOS - The OpenSource Mediator: http://www.berlios.de
#
# File with the main xxxxxxx translation
# translated by xxxxxxxx <xxxxx@xxxx.xxx>
#
# This program is free software. You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 or later of the GPL.
######################################################################

switch($phrase) {

// Top strip
     case "Home": $tmp = ""; break;
     case "About us": $tmp = ""; break;
     case "Partners": $tmp = ""; break;
     case "Contact": $tmp = ""; break;

     case "Logged in": $tmp = ""; break;
     case "Expires": $tmp = ""; break;
     case "Not Logged in": $tmp = ""; break;

// Top title
     case "Open Source Software Announcement &amp; Retrieval":  $tmp = ""; break;

// Menue bar
     case "Recent Apps": $tmp = ""; break;
     case "Q&amp;A": $tmp = ""; break;
     case "Login": $tmp = ""; break;
     case "Logout": $tmp = ""; break;
     case "New User": $tmp = ""; break;
     case "Forgot Password": $tmp = ""; break;
     case "Change User": $tmp = ""; break;
     case "Users": $tmp = ""; break;

     case "Apps Index": $tmp = ""; break;
     case "New Apps": $tmp = ""; break;
     case "Update Apps": $tmp = ""; break;
     case "Pending Apps": $tmp = "";break;
     case "Deleted Apps": $tmp = "";break;
     case "Modified Apps": $tmp = "";break;

     case "Backend": $tmp = ""; break;
     case "Statistics": $tmp = ""; break;

     case "Administration": $tmp = ""; break;
     case "Sections": $tmp = ""; break;
     case "Categories": $tmp = ""; break;
     case "Authors": $tmp = ""; break;
     case "Licenses": $tmp = ""; break;
     case "Check Date": $tmp = ""; break;

     case "Search": $tmp = ""; break;
     case "Language": $tmp = ""; break;
     case "Go": $tmp = ""; break;

// Languages
	 case "English": $tmp = ""; break;
	 case "German": $tmp = ""; break;
	 case "Spanish": $tmp = ""; break;

// sorted by
	 case "sorted by": $tmp = ""; break;
	 case "Date": $tmp = ""; break;
	 case "Importance": $tmp = ""; break;
	 case "Urgency": $tmp = ""; break;
	 case "Name": $tmp = ""; break;

// FAQ
     case "Frequently Asked Questions": $tmp = ""; break;
     case "Question": $tmp = ""; break;
     case "Answer": $tmp = ""; break;

// Apps update
     case "Comment": $tmp = ""; break;
     case "Review": $tmp = ""; break;
     case "Update": $tmp = ""; break;
     case "Delete": $tmp = ""; break;
     case "Undelete": $tmp = ""; break;

// Apps not yet reviewed
     case "Waiting for Review by an Editor": $tmp = ""; break;

// Apps by identifier
     case "Application": $tmp = ""; break;
     case "Others by Author": $tmp = ""; break;
     case "has not yet been reviewed by a $GLOBALS[sys_name] Editor.<br> Please, be patient. It will be surely done in the next time.": $tmp = ""; break;
     case "is modified": $tmp = ""; break;
     case "is deleted": $tmp = ""; break;

// User registration
     case "Register as a new User": $tmp = ""; break;
     case "Username": $tmp = ""; break;
     case "Password": $tmp = ""; break;
     case "Confirm Password": $tmp = ""; break;
     case "Realname": $tmp = ""; break;
     case "Register": $tmp = ""; break;
     case "User Registration": $tmp = ""; break;
     case "Congratulations": $tmp = ""; break;
     case "You have registered on $GLOBALS[sys_name]": $tmp = ""; break;
     case "Your new username is": $tmp = ""; break;
     case "You are now being sent a confirmation email to verify your email address": $tmp = ""; break;
     case "Visiting the link sent to you in this email will activate your account": $tmp = ""; break;
     case "Thank you for registering on the $GLOBALS[sys_name] Site. In order": $tmp = ""; break;
     case "to complete your registration, visit the following URL": $tmp = ""; break;
     case "Enjoy the site": $tmp = ""; break;
     case " -- the $GLOBALS[sys_name] crew": $tmp = ""; break;
     case "Verification of Registration": $tmp = ""; break;
     case "Your account is now activated. Please login": $tmp = ""; break;

// Forget password / Remind me
     case "Register as a new User": $tmp = ""; break;
     case "Remind me": $tmp = ""; break;
     case "Your Username and Password for $GLOBALS[sys_name] is": $tmp = ""; break;
     case "Please keep this e-mail for further reference": $tmp = ""; break;
     case "You will get your Password by e-mail in a couple of minutes": $tmp = ""; break;

// Change User Parameters
     case "Change User Parameters": $tmp = ""; break;
     case "Remind me": $tmp = ""; break;
     case "Modification": $tmp = ""; break;
     case "Creation": $tmp = ""; break;
     case "Permission": $tmp = ""; break;
     case "Change": $tmp = ""; break;
     case "Password and/or E-Mail Address of": $tmp = ""; break;
     case "is changed": $tmp = ""; break;

// Apps by category
     case "Homepage": $tmp = ""; break;
     case "Download": $tmp = ""; break;
     case "Changelog": $tmp = ""; break;
     case "Comments": $tmp = ""; break;
     case "Type": $tmp = ""; break;
     case "Updated": $tmp = ""; break;
     case "Created": $tmp = ""; break;
     case "Stable": $tmp = ""; break;
     case "Development": $tmp = ""; break;
     case "License": $tmp = ""; break;

// New Apps
     case "New Application": $tmp = ""; break;
     case "Application Name": $tmp = ""; break;
     case "Insert": $tmp = ""; break;

// Insert Apps
     case "Insert Application": $tmp = ""; break;
     case "Version": $tmp = ""; break;
     case "Section/Category": $tmp = ""; break;
     case "Red Hat Package": $tmp = ""; break;
     case "Debian Package": $tmp = ""; break;
     case "Slackware Package": $tmp = ""; break;
     case "CVS/SVN Tree": $tmp = ""; break;
     case "Screenshots": $tmp = ""; break;
     case "Mailing List Archive": $tmp = ""; break;
     case "Description": $tmp = ""; break;
     case "Author": $tmp = ""; break;
     case "Depends on": $tmp = ""; break;
	 case "low": $tmp = ""; break;
	 case "medium": $tmp = ""; break;
	 case "high": $tmp = ""; break;

// Update Apps
     case "Update Application": $tmp = ""; break;
     case "Application ID": $tmp = ""; break;
     case "Announcements": $tmp = ""; break;
     case "active": $tmp = ""; break;
     case "pending": $tmp = ""; break;
     case "deleted": $tmp = ""; break;
     case "Check": $tmp = ""; break;

// Comment
     case "Your Comment about": $tmp = ""; break;
     case "Subject": $tmp = ""; break;
     case "Comment": $tmp = ""; break;
     case "Send": $tmp = ""; break;

// Login
     case "$GLOBALS[sys_name] Login": $tmp = ""; break;
     case "Welcome to $GLOBALS[sys_name]": $tmp = ""; break;
     case "You are logged in as": $tmp = ""; break;
     case "with": $tmp = ""; break;
     case "permission": $tmp = ""; break;
     case "Your authentication is valid until": $tmp = ""; break;

// Logout
     case "You have been logged in as": $tmp = ""; break;
     case "Your authentication was valid until": $tmp = ""; break;
     case "This is all over now. You have been logged out": $tmp = ""; break;

// User admin
     case "Action": $tmp = ""; break;
     case "Delete": $tmp = ""; break;
     case "Create User": $tmp = ""; break;
     case "User Creation": $tmp = ""; break;
     case "created": $tmp = ""; break;
     case "User Change": $tmp = ""; break;
     case "User Deletion": $tmp = ""; break;
     case "is deleted": $tmp = ""; break;

// Section admin
     case "Section Administration": $tmp = ""; break;
     case "Insert a Section": $tmp = ""; break;
     case "Rename a Section": $tmp = ""; break;
     case "Delete a Section": $tmp = ""; break;
     case "New Section": $tmp = ""; break;
     case "New Section Name": $tmp = ""; break;
     case "Section": $tmp = ""; break;
     case "Rename": $tmp = ""; break;

// Category admin
     case "Category Administration": $tmp = ""; break;
     case "Insert a Category": $tmp = ""; break;
     case "Rename a Category": $tmp = ""; break;
     case "Delete a Category": $tmp = ""; break;
     case "New Category": $tmp = ""; break;
     case "New Category Name": $tmp = ""; break;
     case "Category": $tmp = ""; break;

// License admin
     case "License Administration": $tmp = ""; break;
     case "Insert a License": $tmp = ""; break;
     case "Rename a License": $tmp = ""; break;
     case "Change a License URL": $tmp = ""; break;
     case "Delete a License": $tmp = ""; break;
     case "New License": $tmp = ""; break;
     case "License URL": $tmp = ""; break;
     case "New License Name": $tmp = ""; break;
     case "New License URL": $tmp = ""; break;
     case "License": $tmp = ""; break;

// Announcements
    case "by": $tmp = ""; break;
    case "on": $tmp = ""; break;
	case "hits": $tmp = ""; break;

// Time-based Navigation
    case "Day": $tmp = ""; break;
    case "Today": $tmp = ""; break;
    case "Week": $tmp = ""; break;

// Search
    case "No Application found": $tmp = ""; break;

// Apps by user
     case "Apps of User": $tmp = ""; break;
     case "No Apps of User exist": $tmp = ""; break;

// Pending Apps
     case "No pending Apps exist": $tmp = ""; break;

// Deleted or modified apps
     case "Is deleted": $tmp = ""; break;
     case "Is modified": $tmp = ""; break;
     case "No deleted Apps exist": $tmp = ""; break;
     case "No modified Apps exist": $tmp = ""; break;

// Users
    case "No": $tmp = ""; break;
    case "All": $tmp = ""; break;

// Developers
    case "Names": $tmp = ""; break;
    case "Unknown": $tmp = ""; break;

// Licences
     case "Apps": $tmp = ""; break;

// Check Date
     case "All dates are consistent": $tmp = ""; break;

// Newsletter
     case "Subscribe Newsletter": $tmp = ""; break;
     case "Subscribe": $tmp = ""; break;
     case "Send newsletter": $tmp = ""; break;
     case "Newsletter was sent at ": $tmp = ""; break;
     case "You have subscribed to $GLOBALS[sys_name] Newsletter": $tmp = ""; break;
     case "Daily Newsletter": $tmp = ""; break;
     case "Weekly Newsletter": $tmp = ""; break;
     case "daily": $tmp = ""; break;
     case "weekly": $tmp = ""; break;

// Statistics
	 case "$GLOBALS[sys_name] Statistics": $tmp = ""; break;
	 case "General $GLOBALS[sys_name] Statistics": $tmp = ""; break;
	 case "Apps by Importance": $tmp = ""; break;
	 case "Apps by Hits": $tmp = ""; break;
	 case "Apps by Homepage Visits": $tmp = ""; break;
	 case "Apps by Downloads": $tmp = ""; break;
	 case "Top downloaded RPM Packages": $tmp = ""; break;
	 case "Top downloaded Debian Packages": $tmp = ""; break;
	 case "Top downloaded Slackware Packages": $tmp = ""; break;
	 case "Apps and Downloads by Urgency": $tmp = ""; break;
	 case "Apps and Downloads by Version Types": $tmp = ""; break;
	 case "Apps and Importance by Sections": $tmp = ""; break;
	 case "Apps by Categories": $tmp = ""; break;
	 case "Apps by Version Numbers": $tmp = ""; break;
	 case "Apps and Downloads by Package Formats": $tmp = ""; break;
	 case "Importance by Licenses": $tmp = ""; break;
	 case "Importance by Email Domains": $tmp = ""; break;
	 case "Apps by Email Domains": $tmp = ""; break;
	 case "Apps by Sections and Email Domains": $tmp = ""; break;
	 case "Apps by Licenses": $tmp = ""; break;
	 case "Apps by Licenses and Email Domains": $tmp = ""; break;

// General Statistics
	 case "Number of Applications in $GLOBALS[sys_name]": $tmp = ""; break;
	 case "Total Number of Insertions and Modifications": $tmp = ""; break;
	 case "Number of Insertions and Modifications during the last week": $tmp = ""; break;
	 case "Number of pending Applications": $tmp = ""; break;
	 case "Number of $GLOBALS[sys_name] authorised Users": $tmp = ""; break;
	 case "Number of Comments on Applications": $tmp = ""; break;
	 case "Number of Licenses listed in $GLOBALS[sys_name]": $tmp = ""; break;
	 case "Number of $GLOBALS[sys_name] Sections": $tmp = ""; break;
	 case "Number of $GLOBALS[sys_name] Categories": $tmp = ""; break;
	 case "Number of Hits on Applications": $tmp = ""; break;
	 case "Number of redirected Homepages": $tmp = ""; break;
	 case "Number of Downloads": $tmp = ""; break;
	 case "Number of redirected Changelogs": $tmp = ""; break;
	 case "Number of redirected CVSs/SVNs": $tmp = ""; break;
	 case "Number of redirected Screenshots": $tmp = ""; break;
	 case "Number of redirected Mailing Lists Archives": $tmp = ""; break;
	 case "SourceWell Version": $tmp = ""; break;

	 case "High Urgency": $tmp = ""; break;
	 case "Medium Urgency": $tmp = ""; break;
	 case "Low Urgency": $tmp = ""; break;
	 case "Stable Version": $tmp = ""; break;
	 case "Development Version": $tmp = ""; break;
	 case "Version Number": $tmp = ""; break;
	 case "Tarballs": $tmp = ""; break;
	 case "Red Hat Packages": $tmp = ""; break;
	 case "Debian Packages": $tmp = ""; break;
	 case "Slackware Packages": $tmp = ""; break;
	 case "Applications listed by their Importance": $tmp = ""; break;
	 case "Applications listed by Number of Tarball-Downloads": $tmp = ""; break;
	 case "Applications listed by Number of Hits": $tmp = ""; break;
	 case "Applications listed by Homepage Visits": $tmp = ""; break;
	 case "Top downloaded Red Hat Packages": $tmp = ""; break;
	 case "Top downloaded Debian Packages": $tmp = ""; break;
	 case "Top downloaded Slackware Packages": $tmp = ""; break;
	 case "Application Importance listed by Sections": $tmp = ""; break;
	 case "Applications listed by Sections": $tmp = ""; break;
	 case "Applications listed by Categories": $tmp = ""; break;
	 case "Applications listed by Licenses": $tmp = ""; break;
	 case "Availability of downloadable Packet Formats": $tmp = ""; break;
	 case "Downloads listed by Packet Formats": $tmp = ""; break;
	 case "Applications listed by Urgency": $tmp = ""; break;
	 case "Downloads listed by Urgency": $tmp = ""; break;
	 case "Applications listed by Version Numbers": $tmp = ""; break;
	 case "Applications listed by Licenses": $tmp = ""; break;
	 case "Applications listed by Version Type": $tmp = ""; break;
	 case "Downloads listed by Version Type": $tmp = ""; break;
	 case "Application Importance listed by Licenses": $tmp = ""; break;
	 case "Application Importance listed by Developer's Email Domains": $tmp = ""; break;
	 case "Applications listed by Developer's Email Domain": $tmp = ""; break;
	 case "Applications listed by Sections and Developer's Email Domain": $tmp = ""; break;
	 case "Applications listed by Licenses and Developer's Email Domain": $tmp = ""; break;

// Errors
     case "Access denied": $tmp = ""; break;
     case "Error": $tmp = ""; break;
     case "does not exist": $tmp = ""; break;
     case "Change User Parameters failed": $tmp = ""; break;
     case "No Application ID specified": $tmp = ""; break;
     case "No Application Name specified": $tmp = ""; break;
     case "Please select": $tmp = ""; break;
     case "Parameter missing": $tmp = ""; break;
     case "and": $tmp = ""; break;
     case "User": $tmp = ""; break;
     case "already exists": $tmp = ""; break;
     case "Please select a different Username": $tmp = ""; break;
     case "Please enter": $tmp = ""; break;
     case "Either your Username or E-Mail Address is unknown": $tmp = ""; break;
     case "Please try again": $tmp = ""; break;
     case "If you are not yet a registered User, please select": $tmp = ""; break;
     case "Verification of Registration failed": $tmp = ""; break;
     case "User Change failed": $tmp = ""; break;
     case "Registration of new User failed": $tmp = ""; break;
     case "Database Access failed": $tmp = ""; break;
     case "User Deletion failed": $tmp = ""; break;
     case "No more Apps for this day": $tmp = ""; break;
     case "Either your Username or Password are invalid": $tmp = ""; break;
     case "The passwords are not identical": $tmp = ""; break;
     case "Please try again": $tmp = ""; break;
     case "License description is not available": $tmp = ""; break;

// New Translations for SourceWell 1.1

// stats.php
    case "Number of Insertions and Modifications in the last day": $tmp = ""; break;
    case "Number of today's visitors": $tmp = ""; break;
    case "Today": $tmp = ""; break;
    case "Version Number":  $tmp = ""; break;
    case "High Urgency": $tmp = ""; break;
    case "Medium Urgency": $tmp = ""; break;
    case "Low Urgency": $tmp = ""; break;

// admuser.php
    case "User Administration": $tmp = ""; break;
    case "There can only be one anonymous user in the system": $tmp = ""; break;
    case "The anonymous permission is incompatible with another type of permission": $tmp = ""; break;

// inscat.php and inssec.php
    case "Former category": $tmp = ""; break;
    case "in Section": $tmp = ""; break;
    case "has been renamed to": $tmp = ""; break;
    case "affecting": $tmp = ""; break;
    case "applications": $tmp = ""; break;
    case "already exists!": $tmp = ""; break;
    case "Category not specified": $tmp = ""; break;
    case "This is the unique category of the section. For deleting it, you should delete the whole section.": $tmp = ""; break;
    case "If you press another time the Delete-button you will delete": $tmp = ""; break;
    case "applications that are actually in the": $tmp = ""; break;
    case "category": $tmp = ""; break;
    case "Delete Category": $tmp = ""; break;
    case "Delete": $tmp = ""; break;
    case "Deletion succesfully completed.": $tmp = ""; break;
    case "Deletion succesfully completed affecting": $tmp = ""; break;
    case "applications": $tmp = ""; break;
    case "has been added succesfully to the database": $tmp = ""; break;
    case "Category not specified": $tmp = ""; break;
    case "Warning!": $tmp = ""; break;
    case "If you press another time the Delete-button you will delete the": $tmp = ""; break;
    case "categories and": $tmp = ""; break;
    case "applications that are actually in the": $tmp = ""; break;
    case "section": $tmp = ""; break;
    case "Delete Section": $tmp = ""; break;

// inslic.php

    case "License name not specified": $tmp = ""; break;
    case "has a new URL:": $tmp = ""; break;
    case "New URL not specified": $tmp = ""; break;
    case "If you press another time the Delete-button you will alter": $tmp = ""; break;
    case "applications that have actually license": $tmp = ""; break;
    case "That license already exists!": $tmp = ""; break;
    case "with URL": $tmp = ""; break;
    case "has been added succesfully to the database": $tmp = ""; break;
    case "License URL not specified": $tmp = ""; break;
    case "License not specified": $tmp = ""; break;
    case "Delete License": $tmp = ""; break;

// admcomment.php and comment.php
    case "Posted on": $tmp = ""; break;
    case "Modify": $tmp = ""; break;
    case "Comment about": $tmp = ""; break;
    case "Delete this comment? (please, think there's no way for undoing comment deletion)": $tmp = ""; break;
    case "Yes, Delete": $tmp = ""; break;
    case "No, Just Modify": $tmp = ""; break;
    case "Comment Deleted": $tmp = ""; break;
    case "Selected Comment was deleted": $tmp = ""; break;

// admfaq.php and insfaq.php

    case "Enter a New Frequently Asked Question": $tmp = ""; break;
    case "Frequently Asked Questions Administration": $tmp = ""; break;
    case "Delete this faq? (please, think there's no way for undoing comment deletion)": $tmp = ""; break;
    case "Create": $tmp = ""; break;
    case "FAQ Deleted": $tmp = ""; break;
    case "FAQ Administration": $tmp = ""; break;
    case "The following FAQ has been modified": $tmp = ""; break;
    case "The following FAQ has been inserted in this language": $tmp = ""; break;

// admdate.php
    case "Modification date": $tmp = ""; break;
    case "History date": $tmp = ""; break;

// nladm.php
    case "The Mailing Lists are not enabled": $tmp = ""; break;
    case "daily newsletter for": $tmp = ""; break;
    case "weekly newsletter for": $tmp = ""; break;
    case "Newsletter was sent at ": $tmp = ""; break;
    case "Send newsletter": $tmp = ""; break;

// footer.inc
    case "System Credits": $tmp = ""; break;

// login.php3
    case "Anonymous login": $tmp = ""; break;
    case "If you are not registered and/or you do not want to, you can login as an anonymous user by entering": $tmp = ""; break;
    case "as user name and": $tmp = ""; break;
    case "as password.": $tmp = ""; break;

// configure.php


// If no translation available, keep the original phrase
// Please, translation of this is not needed!
     default: $tmp = "$phrase"; break;
}
?>
