<html>
<head>
<style TYPE="text/css">
<!--
A { text-decoration: none; }
A:hover { text-decoration: underline; }
H1 { font-family: arial,helvetica,sans-serif; font-size: 18px; font-weight: bold;}
H2 { font-family: arial,helvetica,sans-serif; font-size: 14px; font-weight: bold;}
BODY,TD { font-family: arial,helvetica,sans-serif; font-size: 12px; }
TH { font-family: arial,helvetica,sans-serif; font-size: 12px; font-weight: bold; }
//-->
</style>
<title><?php echo "$sys_name - $sys_title" ?></title>
</head>

<body bgcolor="white" text="black">
<h1><?php echo "$sys_name - Installation and configuration check" ?></h1>
